/*
Convert CSV (generated/scraped_export.csv or generated/approved_questions.csv) to src/data/questions.js
Usage: node tools/csv_to_questions.js generated/approved_questions.csv
*/
import fs from 'fs';
import path from 'path';
import { parse } from 'csv-parse/sync';
const csvPath = process.argv[2] || 'generated/scraped_export.csv';
const raw = fs.readFileSync(csvPath,'utf8');
const rows = parse(raw, { columns: true, skip_empty_lines: true, trim: true });
const sectionsMap = {};
rows.forEach((r,i)=>{
  const section_id = (r.section_id || 'misc').trim();
  const subtopic_id = r.subtopic_id ? r.subtopic_id.trim() : null;
  const qobj = { id: r.question_id || `${section_id}-${subtopic_id||'gen'}-${i+1}`, q: (r.question||'').replace(/\r?\n/g,' ').trim(), options: [r.option_1||'', r.option_2||'', r.option_3||'', r.option_4||''].map(o=>o.trim()), a: Number.isFinite(Number(r.answer_index)) ? parseInt(r.answer_index,10) : 0 };
  if(!sectionsMap[section_id]) sectionsMap[section_id] = { id: section_id, title: section_id, description:'', questions: [], subtopics: {} };
  if(subtopic_id){
    if(!sectionsMap[section_id].subtopics[subtopic_id]) sectionsMap[section_id].subtopics[subtopic_id] = { id: subtopic_id, title: subtopic_id, questions: [] };
    sectionsMap[section_id].subtopics[subtopic_id].questions.push(qobj);
  } else {
    sectionsMap[section_id].questions.push(qobj);
  }
});
const SECTIONS = Object.values(sectionsMap).map(sec=>{
  const subs = Object.values(sec.subtopics||{}).map(st=>({ id: st.id, title: st.title, questions: st.questions }));
  return { id: sec.id, title: sec.title, description: sec.description || '', ...(sec.questions && sec.questions.length ? { questions: sec.questions } : {}), ...(subs.length ? { subtopics: subs } : {}) };
});
const outPath = path.join(process.cwd(),'src','data','questions.js');
const content = `// Auto-generated by tools/csv_to_questions.js\nexport const SECTIONS = ${JSON.stringify(SECTIONS, null, 2)};\n`;
fs.writeFileSync(outPath, content, 'utf8');
console.log('Wrote', outPath);
